/*
 * generated by Xtext 2.9.0.v201507170721
 */
package org.xtext.example.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IotdslRuntimeModule extends org.xtext.example.mydsl.AbstractIotdslRuntimeModule {

}
